### ISSUE TITLE
기획 회의

### ISSUE THREAD

**Issue by chichoon** [42Blank/ft_transcendence#1]
- 향후 계획 수립
- 시간 계획
- 프로젝트 구조 잡기

**Comment by devleomk1** [comment]
### 요구사항
1. 웹사이트는 Single-page application으로 동작해야함
2. 브라우저의 Back / Forward 버튼이 동작해야함
3. 최신버전 Chrome, Firefox, Safari에서 정상 작동해야함.
4. OAuth 시스템을 통해 42intra에 로그인 해야함
5. 웹사이트에 표시할 유니크한 닉네임을 선택할 수 있어야함
6. 유저 아바타를 업로드 할 수 있어야하고, 업로드 안했으면 기본 아바타가 설정되어야함
7. 유저는 2차 인증을 사용할 수 있어야함
8. 유저는 다른 유저를 친구로 추가 할 수 있어야하고 그들의 상태를 볼 수 있어야함
    - online
    - ofline
    - in a game
    - 기타
9. 유저 프로필에서 다음을 표기 해야함
    1. 승/패
    2. 레더 레벨
    3. 어치브먼트
    4. 기타 등등
10. 유저 채팅
    1. 채널(채팅방) 생성이 가능해야함
    2. 채널은 공개/비공개(비밀번호를 사용한) 설정이 가능해야함
    3. 유저는 다른 유저에게 DM을 보낼 수 있어야함
    4. 유저는 다른 유저를 차단 할 수 있어야함
    5. 차단을 하면 그 유저의 메세지가 더 이상 보이면 안됨
    6. 채널을 생성하면 채널 **소유자**(Owner)가 된다. 채널을 떠나기 전까지!
        1. 채널 **소유자**는 비밀번호 설정/변경/삭제가 가능하다.
        2. 채널 **소유자**는 채널 **관리자**(administrator)이기도 하다.
        3. 소유자와 관리자는 다른 유저를 관리자로 권한을 변경 할 수 있다.
        4. 채널 관리자는 밴을 하거나 제한된 시간동안 다른 유저를 음소거 할 수 있다.
    7. 유저는 채팅 인터페이스를 통해 다른 유저를 퐁 게임에 초대 할 수 있다.
    8. 유저는 채팅 인터페이스를 통해 다른 유저의 프로필에 접근 할 수 있어야 한다.
11. Pong 게임
    1. 유저는 실시간 퐁 게임을 웹사이트에서 다이렉트로 플레이 가능하다.
    2. 매치 메이킹 시스템 : 유저는 자동 매칭이 될때 까지 queue에서 대기해야함
    3. 캔버스에 그리든 3D든 못생겨도 되지만, original Pong(1972)에 충실 해야한다.
    4. 게임 커스터마이즈 옵션이 있고 일반 모드랑 선택이 가능하다.
    5. 게임은 실시간 반응 게임이다.
    6. 다른 유저는 게임을 하는 플레이어를 관전 할 수 있으나 간섭 할 순 없다.

**Comment by Skyrich2000** [comment]
# 로그인 화면
<img width="396" alt="스크린샷 2023-01-15 오전 1 59 16" src="https://user-images.githubusercontent.com/46391729/212485224-b23bc5d8-ead4-4fd8-91d2-fbe3db1c1ab5.png">

* 로그인후 바로 채팅화면으로 넘어간다.

# 채팅화면 
<img width="575" alt="스크린샷 2023-01-15 오전 1 59 44" src="https://user-images.githubusercontent.com/46391729/212485238-8f3e38da-8eb0-4eab-abb4-6896701f3813.png">
<img width="415" alt="스크린샷 2023-01-15 오전 2 00 09" src="https://user-images.githubusercontent.com/46391729/212485272-5353389a-51ca-4e81-910c-2a4a51bd5b62.png">

# 게임화면
<img width="609" alt="스크린샷 2023-01-15 오전 2 00 51" src="https://user-images.githubusercontent.com/46391729/212485296-229bacf5-9856-4d30-b57b-37931a3fb109.png">

# 프로필 화면
<img width="391" alt="스크린샷 2023-01-15 오전 2 01 03" src="https://user-images.githubusercontent.com/46391729/212485337-2e279c79-28c8-4f75-87b5-69d35fb5de54.png">
