### ISSUE TITLE
Frontend: 채팅방/게임방 추가 버튼 화면 고정 문제

### ISSUE THREAD

**Issue by devleomk1** [42Blank/ft_transcendence#103]
<img width="1150" alt="스크린샷 2023-02-18 오후 10 01 12" src="https://user-images.githubusercontent.com/73428595/219867202-7208dd11-1067-437e-af02-8874967cac6d.png">

게임방, 채팅방 생성 버튼이 화면에 고정되어 있습니다.
목록이 늘어나 스크롤이생기면 같이 안내려가고 그자리에 붙어 있습니다.
브라우저 좌우 크기를 조절하면 정상적으로 따라 갑니다.

스크롤을 해도 고정된 위치에 있도록 수정하면 될 것 같아요.

+ 목록이 2열만 생성되는건 안고쳐도 될듯

**Comment by chichoon** [comment]
![icon_4](https://user-images.githubusercontent.com/37893979/219873389-f71886c9-a06c-4d43-8eee-d2b3388dcf2e.png)
