### ISSUE TITLE
Health: 일찍 자기

### ISSUE THREAD

**Issue by chichoon** [42Blank/ft_transcendence#119]
![image](https://user-images.githubusercontent.com/37893979/219936731-9631e10b-ba65-4011-9134-1cc06befe134.png)

00시에 자겠습니다. 00시 ~ 09시까진 어떠한 이슈에도 대응 안하겠습니다 (오야스미 모드 켜놓음)
근데 어차피 슬랙 알림 꺼놔서 저한테 전하실 이슈 있으면 태그 거셔도 됨 (띄어쓰기안해도 된다는뜻)

내 몸에 버그날거같아서 라벨은 버그

**Comment by Skyrich2000** [comment]
실패
