### ISSUE TITLE
Feat: 친구 목록에 진짜 친구만 뜨게 만들기

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#126]
지금은 사이드바에 id: 1~5 로 고정된 더미만 있음
이것을 진짜 친구목록에 있는 친구만 뜨도록 하기

근데 그러면 친구가 아닌 사람은 어떻게 친구추가 하지 ?

**Comment by chichoon** [comment]
#58 과 중복이슈입니다
