### ISSUE TITLE
Feat/profile-match-history : 매치 히스토리 구현

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#128]
TODO
- [ ] 매치 히스토리 API 상의하기
- [ ] 매치 히스토리 더미를 이용해 구현
- [ ] API 적용

**Comment by ft-jasong** [comment]
match history dto
매치 고유번호 id : number
winner : User
loser User : User
createdAt : Date

**Comment by stripy1026** [comment]
> match history dto 매치 고유번호 id : number winner : User loser User : User createdAt : Date

확인 !
