### ISSUE TITLE
Feat/profile-achievement : 업적 구현

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#129]
TODO
- [x] 업적 API 상의하기
- [x] 업적 더미를 이용하여 구현
- [ ] API 콜로 구현

**Comment by ft-jasong** [comment]
엔티티 정리입니다
1. 업적 고유 번호 - id
2. 업적 이름 : name
3. 업적 설명 : description
4. 업적 이미지 : image

업적 id별 종류
1. 첫 게임 승리
2. 게임 3번 승리
3. 연속 3번 게임 승리
4. 첫 게임 패배 
5. 게임 3번 패배 
6. 연속 3번 게임 패배
7. 첫 친구 추가
8. 친구 3명 추가

**Comment by stripy1026** [comment]
dto 밸류에 업적 달성일 이 있으면 좋지 않을까요 ?

**Comment by ft-jasong** [comment]
@stripy1026 일단 엔티티에 넣어보겠습니다 !!

**Comment by ft-jasong** [comment]
achievedAt으로 변수 네이밍 설정했습니다 !
