### ISSUE TITLE
feat/profile: [BUG] deleteFriend 작동 안함 !

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#140]
Bug process

1. main branch 에서 테스트
2. 친구 목록에서 아무나 찍어서 들어감 (ex id:2) 
3. 친구/차단 리스트가 없다면, 친구 추가 하거나 차단함 (ex Add Friend 클릭)
4. 다시 친구/차단 리스트에서 삭제함 (ex Unfriend 클릭)
5. DELETE https://transcendence.42world.kr:8084/friend 400 (Bad Request)
에러 메세지 발생 !

https://transcendence.42world.kr/ 에서도 동일한 버그 발생

**Comment by chichoon** [comment]
![dbaa5dd99d02339c83d4e02a916affaf85b71e623c6989772b36537335e2fdf6](https://user-images.githubusercontent.com/37893979/220344082-9b8261dc-937d-4681-bf05-46b4b867b680.png)
