### ISSUE TITLE
Feat/profile: Match History 에 1v1/Ladder 구분 추가하기

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#147]
>Each user should have a Match History including 1v1 games, ladder, and anything else useful. Anyone who is logged in should be able to consult it.
*from subject
----

TODO
- [ ] 매치 히스토리에 1v1 과 래더 구분하기
래더 탭과 1v1 탭 구분 ? vs 각각 매치에 1v1 인지 래더인지 표시 ?

- [ ] 매치 히스토리 dto 에 매치 타입이 1v1 인지 래더인지 추가해야 할듯 ?

**Comment by ft-jasong** [comment]
구분 안하기로 했으므로, Close하도록 하겠습니다!
