### ISSUE TITLE
Feat/Profile: 샘플 아바타 더 추가하기

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#202]
TODO:
- [ ]  샘플 아바타 리스트 컴포넌트 추가

## 도움 !
````
const imageRef = useRef<HTMLImageElement>(null);

  function handleClickImage() {
    setImageUrl(imageRef.current.src);
  }
````

현재 샘플 아바타 클릭시 이함수를 콜하는데,
아바타 리스트로 바꾸려면 imageRef 말고
함수 인자로 event를 받아서 그거의 currentTarget.firstChild 를 수정하고싶음.
근데 콘솔 로그 찍어보면
````
console.log(currentTarget.firstChild);
output:
<img class="css-1ckld55" src="/pochita_sample.png" width="100" height="100" alt="pochi">
````
이렇게 잘 나오는데 
src 를 참조하려고 하면
````
console.log(e.currentTarget.firstChild.src);
error:
Property 'src' does not exist on type 'ChildNode'.
````
이렇게 나옴 ..
어떻게 해야 src 를 참조할 수 있을까요 ?

## Solution
> https://www.designcise.com/web/tutorial/how-to-fix-property-does-not-exist-on-type-eventtarget-typescript-error

요약
- 마우스 클릭 이벤트 (MouseEvent) 타입의 타겟
`e.target`  혹은 `e.currentTarget` 의 id, src 등 프로퍼티에 접근 할 수 없다.
- 그 이유는, 마우스 이벤트의 타겟이 꼭 Element 라고 확신할 수 없기 때문 !
- 마우스 이벤트의 타겟으로는 XMLHttpRequest, FileReader, AudioNode, AudioContext, etc. 등등이 올 수 있다고 한다.
- 따라서, 우리 이벤트의 타겟이 반드시 HTMLInputElement 가 올것이라고 Type asserting 을 해 줘야 한다 !

````
console.log(e.target.src); // 이렇게 하면 src를 찾지 못함
console.log((e.target as HTMLInputElement).src); // Correct !
output:
https://localhost:3000/pochita_sample.png
````

type asserting 이 위험하다고 생각했지만, 꼭 필요한 경우도 있다 !

**Comment by devleomk1** [comment]
샘플 아바타를 더 추가한다는게 무슨 의미인가유? 더 다양한 샘플 아바타가 필요하다는 건가요?

**Comment by chichoon** [comment]
42월드처럼 파일업로드 없이도 선택할 수 있는 아바타 폭을 넓히신다는 의미 같네요
사실 굳이싶긴한데!!
