### ISSUE TITLE
Phaser 예제 컴포넌트 프론트에 추가

### ISSUE THREAD

**Issue by devleomk1** [42Blank/ft_transcendence#27]
TO DO
1. Phaser로 작성한 게임 예제를 컴포넌트로 만든다.
2. 예제를 플레이 가능한 페이지를 구현한다.
3. 컴포넌트화된 예제를 우리 트센 프론트 페이지에서 구현 한다.

**Comment by devleomk1** [comment]
![Feb-11-2023 17-40-51](https://user-images.githubusercontent.com/73428595/218248973-5305673e-1b6b-4936-b686-068669047783.gif)

### 문제
원하지 않은 위치(root)에 게임이 생성되는 문제 발생.

### 원인 
Phaser가 컴포넌트로 동작하지 않아서 생긴 문제.

### 해결
[@ion-phaser/react](https://www.npmjs.com/package/@ion-phaser/react)를 사용해 phaser 게임을 컴포넌트로 묶는다.

**Comment by Skyrich2000** [comment]
이거 혹시 작업중인 브랜치 있으신가영

**Comment by devleomk1** [comment]
@Skyrich2000 
1. https://github.com/42Blank/ft_transcendence/tree/feat/phaser-example 에서 작업중입니다.
2. ion-phaser/react로 원하지 않는 곳에 게임 출력되는 건 수정했는데
3. 출력된 게임에서 에러 발생 해서 수정하고 있습니당. 
  <img width="487" alt="스크린샷 2023-02-11 오후 10 43 28" src="https://user-images.githubusercontent.com/73428595/218261229-1937c338-9e02-41be-859c-4e74f47e43a9.png">
4. 잘 출력되던 이미지 로드가 ion-phaser/react 쓰고 안되는데 왜그러는 건지 몰루...? 😵‍💫
5. ion-phaser/react 쪽 예제 베이스로 분석하는 중 😞

**Comment by devleomk1** [comment]
![Feb-11-2023 23-36-40](https://user-images.githubusercontent.com/73428595/218263775-5c730086-a9a9-45e4-bc1b-01f6b74e7051.gif)

🐛 버그 픽스 완료

- 게임 탭에서 예제 게임 출력 성공
- 이미지 로드 확인
- 키보드 입력 확인 완료
