### ISSUE TITLE
front 로그인후, userinfo 가 update 되지 않는 이유

### ISSUE THREAD

**Issue by Skyrich2000** [42Blank/ft_transcendence#34]
```
    getFtCallbackCode(code).then(() => {
      nav(ROUTE.CHAT);
    });
```
여기서 nav를 해도 getCurrentUserInfo 가 안되서 updateCurrentUserInfo 같은게 필요해보입니다.

**Comment by chichoon** [comment]
![image](https://user-images.githubusercontent.com/37893979/218111960-105b0513-c670-40b9-937b-23c2e939bd54.png)

**Comment by chichoon** [comment]
이부분 `useQuery` 도입하는 걸로 해결 보겠습니다

![93c5e99cd40b24cdfb9dba5309385aa337270526862d944038346d54cf49ae76](https://user-images.githubusercontent.com/37893979/218120912-f001044d-b605-4154-af12-0e4882e635f5.png)

**Comment by chichoon** [comment]
useQuery 도입해서 해결 했습니당

![image](https://user-images.githubusercontent.com/37893979/218128662-78e1294b-7055-4084-ac7f-a296fa2b2671.png)
