### ISSUE TITLE
Frontend: 크롬 시크릿모드, 사파리에서 로그인 안 되는 이슈

### ISSUE THREAD

**Issue by chichoon** [42Blank/ft_transcendence#43]
![addbe8b0e3cd6eea90631ea9212b8cb41eb78b44de07f76db1315b37856949e4](https://user-images.githubusercontent.com/37893979/218266047-fa65a698-982a-4ab0-b7dd-be839c1401c9.png)

나도 모르겠어 왠지..

**Comment by chichoon** [comment]
배포판은 잘 동작하는 것 확인했습니다. 아마 localhost 가 크로스 도메인 이슈로 쿠키저장을 안 하는듯해요

**Comment by devleomk1** [comment]
평가 항목에 구글크롬을 포함한 2개이상의 브라우저에서 구현해야해서,
클러스터 아이맥에서 사용가능한 브라우저만 검사해볼께요. (되도록 크로미움 베이스로)

**Comment by devleomk1** [comment]
로컬 호스트 아이맥 기준
Chrome, Opera 브라우저 잘 되는 거 확인.
