### ISSUE TITLE
Feat: 상하로 움직이는 Paddle 만들기

### ISSUE THREAD

**Issue by devleomk1** [42Blank/ft_transcendence#45]
![pong_paddle](https://user-images.githubusercontent.com/73428595/218266312-68400895-fe9e-4902-befa-498d2cbdbde9.png)

### To Do

- [x] 직사각형 패들 Phaser로 그리기
- [x] 패들을 게임 화면 내부에서만 움직이도록 제한하기

**Comment by devleomk1** [comment]
![Feb-12-2023 01-21-55](https://user-images.githubusercontent.com/73428595/218269110-af195ecc-62da-437d-b401-5d3a37aaf329.gif)

- 직사각형 패들을 화면 내부에서만 움직이도록 제한함.
- world 판정 해서 패들이 월드 밖으로 못나가도록 구현 하려고 했으나 실패
- physics로 구현이 아닌 직접 키보드 입력으로 위치 수정이라 그런듯?
- update에서 Clamp로 못 벗어나게 막아 두긴 했으나 차후에 연산 문제 생기면 수정 할꺼임

**Comment by chichoon** [comment]
지소캉 바보
