### ISSUE TITLE
Pong: Socket.io로 멀티플레이 연결 구현

### ISSUE THREAD

**Issue by devleomk1** [42Blank/ft_transcendence#77]
### 구현 해야할 것
 1. 플레이어 간 1:1 연결
 2. 관전자들(다수)에게 브로드캐스팅

### 주고 받을 데이터
 - PlayerLeft.Paddle.y 좌표
 - PlayerRight.Paddle.y 좌표
 - PlayerLeft.Score
 - PlayerRight.Score
 - Ball.x 좌표
 - Ball.y 좌표
 - (Opt) Velocity?:  #56 구현시 필요함, 일단 보류

**Comment by Skyrich2000** [comment]
일단 연습용 소켓 통신

ping { message: string } -> pong { message: string }

새로운 유저 들어오면 -> hello { nickname: string }

**Comment by devleomk1** [comment]
Socket 연결을 `useHandleSocket.ts`을 기반으로 구현현하였으나,
class형식을 사용하는 Phaser 씬 내부에서 사용하기에 코드가 복잡해지는 문제가 생김.

Phaser 내부에서 바로 소켓 연결하는 식으로 바꿀 예정
