### ISSUE TITLE
Feat/profile 페어프로그래밍 전에 끝내야 할 것들

### ISSUE THREAD

**Issue by stripy1026** [42Blank/ft_transcendence#80]
TODO

- [x] useGetUser axios.get 삼항연산자로 분기 합치기
- [x] @Skyrich2000  리뷰 중에 혼자 할 수 있는거 고치기

**Comment by chichoon** [comment]
인초가 운전하는 폭주기관차

**Comment by stripy1026** [comment]
![Ekv71NqVcAA448n](https://user-images.githubusercontent.com/62825700/219524890-893be305-dde4-4443-bfa5-968a57bd0dcb.png)

그걸 막는 지최마
